# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.base_mac = nil

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
    vb.linked_clone = true
  end

  config.vm.define "gfs01" do |gfs|
    gfs.vm.provider "virtualbox" do |vb|
      vb.name = "gfs01"
    end
    gfs.vm.network "private_network", ip: "192.168.111.11"
    gfs.vm.provision "bootstrap", type: "shell" do |s|
      s.path = "bootstrap.sh"
      s.args = [ "gfs01" ]
    end
    gfs.vm.provision "user-init", type: "shell", privileged: false, path: "user-init.sh"
  end

  config.vm.define "gfs02" do |gfs|
    gfs.vm.provider "virtualbox" do |vb|
      vb.name = "gfs02"
    end
    gfs.vm.network "private_network", ip: "192.168.111.12"
    gfs.vm.provision "bootstrap", type: "shell" do |s|
      s.path = "bootstrap.sh"
      s.args = [ "gfs02" ]
    end
    gfs.vm.provision "gluster-init", type: "shell", path: "gluster-init.sh"
    gfs.vm.provision "user-init", type: "shell", privileged: false, path: "user-init.sh"
  end

  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "$HOME/.ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "$HOME/.ssh/id_rsa.pub"

end
