#!/bin/bash
# Check presence of environment variables
TRAVIS_BUILD_DIR="${TRAVIS_BUILD_DIR:-.}"
DOCKER_EMAIL="${DOCKER_EMAIL:-none@none@none.com}"
DOCKER_USERNAME="${DOCKER_USERNAME:-none}"
DOCKER_PASSWORD="${DOCKER_PASSWORD:-none}"
WSPACE_USERNAME="${WSPACE_USERNAME:-none}"
WSPACE_PASSWORD="${WSPACE_PASSWORD:-none}"
NFS_SERVER_ADDRESS="${NFS_SERVER_ADDRESS:-none}"

echo "##### Deploy sample EOEPCA system on cluster #####"
ansible-playbook  --extra-vars "DOCKER_EMAIL=$DOCKER_EMAIL DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD WSPACE_USERNAME=$WSPACE_USERNAME WSPACE_PASSWORD=$WSPACE_PASSWORD NFS_SERVER_ADDRESS=$NFS_SERVER_ADDRESS" \
                  -i inventory/cf2-kube/hosts eoepca.yml
