# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.base_mac = nil

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
    vb.linked_clone = true
  end

  config.vm.define "nfs" do |node|
    node.vm.hostname = "nfs01"
    node.vm.network "private_network", ip: "192.168.200.11"
  end

  config.vm.provision "shell", name: "nfs-setup", path: "nfs-setup.sh"

end
