@startuml
title User Managed Access (UMA) Flow

participant "LoginService\n[Token Endpoint]" as login order 5
participant "Client\ne.g. Jupyter\nNotebook" as client order 10
participant PEP as pep order 30
participant "Resource\nServer\n(e.g. ADES)" as resource order 40

autonumber
client -> pep : request_resource\n[naive attempt]
client <- pep : unauthorized : (401, ticket)
login <- client : request_access(id_token, ticket, client_credentials)
login -> login : Policy Check (via PDP)
login -> client : authorized : (200, RPT)
client -> pep : request_resource(RPT)
pep -> resource : request_resource
pep <- resource : resource
client <- pep : resource

@enduml
