FROM ubuntu

RUN apt update && apt -y full-upgrade

RUN apt -y install curl

RUN curl -sO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl

RUN chmod +x kubectl

ENTRYPOINT [ "./kubectl", "proxy", "--port=8080" ]
