#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}

trap onExit EXIT

exec docker run --name mkdocs -u $(id -u):$(id -g) --rm -it -v ${PWD}:/docs squidfunk/mkdocs-material "$@"
