#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}

trap onExit EXIT

exec docker run --name mkdocs-serve -u $(id -u):$(id -g) --rm -it -p 8000:8000 -v $(dirname ${PWD}):/docs squidfunk/mkdocs-material serve -f docs/mkdocs.yml --dev-addr 0.0.0.0:8000
